# Generated by Django 4.1.1 on 2022-09-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIStripe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count_in_basked',
            field=models.IntegerField(default=0),
        ),
    ]
