# Generated by Django 4.1.1 on 2022-09-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIStripe', '0002_item_count_in_basked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='count_in_basked',
        ),
    ]
