version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    user: 1000:1000
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    tty: true
    build: .
    # user: 1000:1000
    command: python3 manage.py runserver 0.0.0.0:8000 #dev
    #command: python3 manage.py runserver 0.0.0.0:8000 --insecure #prod
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db